/* ============================================================================\
|                                                                              |
|   Filename:       Label_data_with_ODKmeta.do                                 |
|   Author:         Benjamin Faguer (@benjaminFaguer)                          |
|   Date:           12 August 2020                                             |
|   Project name:   Stata_ODK                                                  |
|   Objective:      Label and shape data downloaded form ODK with ODKmeta      |
|   Revised by:                                                                |
|   Revision date:                                                             |
|   Stata version:  Stata IC version 15.1                                      |
|   Script version: 1.0                                                        |
|                                                                              |
|   Input:                                                                     |
|   Output:                                                                    |
|   Master file:                                                               |
|                                                                              |
\=============================================================================*/
version 15
set more off
clear

cd $workDir
// Make sure the folder where the do-files generated by odkmeta will be exported
// exists.
cap mkdir "$workDir/odkmeta_do-files"

/* Make sure `odkmeta` is installed
   If you don't know or if you know it's not installed yet, 
   uncomment the following line                                               */
// ssc install odkmeta

/* We need the original form definitions for proper labeling of the variables.
    These should have been prepared already, and exported as two csv files:
        - One for the 'survey' worksheet
        - One for the 'choices' worksheet
    If not, please use -help odkmeta- to see how to do it.
    For the purpose of the script, they should be named as such:
        - FormID_survey.csv
        - FormID_choices.csv
    They should be stored in a subfolder at the root of your working directory
    named "odkmeta".

    First, we prepare the do-files which will clean the forms' datasets with the 
    -odkmeta- command.
*/
foreach form of global form_id {
    di "Running ODKmeta for `form'…"
    odkmeta using "$workDir/odkmeta_do-files/`form'.do",                     ///
        csv("$workDir/csv/`form'.csv")                                       ///
        survey("$workDir/odkmeta/`form'_survey.csv")                         ///
        choices("$workDir/odkmeta/`form'_choices.csv") replace
    di "Done." char(10)
    
}

// Then, we run the newly created do-files.
foreach form of global form_id {
        di "Labelling `form'…"
        run "$workDir/odkmeta_do-files/`form'.do"
        di "Done." char(10)
}

// Now all the different forms should be stored in the "csv" directory, 
// alongside the exported csv files from ODK, but now in Stata format.
